#!/bin/bash

APPNAME="mx-packageinstaller-categories"

echodo() {
  echo "${@}"
  ${@}
}

# prepare transifex 
if [ ! -s  .tx/config ]; then
   mkdir -p .tx
   cat <<EOF > .tx/config
[main]
host = https://www.transifex.com

[antix-development.$APPNAME]
file_filter = ./${APPNAME}_<lang>.txt
source_file = ${APPNAME}_en.txt
source_lang = en
type = txt
EOF
fi    

# get all translations
if command -v tx >/dev/null; then
   echodo tx pull -r antix-development.$APPNAME  --all
fi

