#!/bin/bash
	

#check for presence of mx16 repo already
if [ "$(grep /repo/ /etc/apt/sources.list.d/mx.list|grep -m 1 mx16)" = "" ]; then
	echo "Adding MX16 repository to /etc/apt/sources.list.d/mx.list"
	echo "#MX16 repo">>/etc/apt/sources.list.d/mx.list
	new_list=$(grep /repo/ /etc/apt/sources.list.d/mx.list|grep -m 1 mx15 |sed s/mx15/mx16/)
	echo $new_list " added to sources"
	echo $new_list>>/etc/apt/sources.list.d/mx.list
else
	echo "mx16 repo already exists"
fi
echo ""
echo "Ready to Update Sources"
echo ""
read -p "Press ENTER to continue"
apt-get update
defaults_check=$(apt-cache policy desktop-defaults-xfce-mx16 |grep mx16/main|awk {'print $1'})
echo "defaults check " $defaults_check

#check to make sure desktop-defaults-xfce-mx16 exists
if [ "$defaults_check" = "500" ]; then
	echo "found, proceed"
	# remove mx-event-sounds and desktop-defaults-xfce-mx
	read -p "Remove and replace desktop-defaults.  Press ENTER to continue"
	apt-get remove -y mx-event-sounds desktop-defaults-xfce-mx
	apt-get install -y desktop-defaults-xfce-mx16
	#install extra apps
	apt-get install apt-xapian-index mx16-artwork mx16-artwork-extras icedtea-8-plugin lightdm-gtk-greeter-mx16 mx-apps
	#dist-upgrade to polish things off
	apt-get dist-upgrade
else
	echo "There is an error.  desktop-defaults-xfce-mx16 is not available."
	exit 0
fi
exit 0

	
